### ISSUE TITLE
Twitch provider

### ISSUE THREAD

**Issue by alexweininger** [mjangir/nestjs-hybrid-auth#5]
Hey! 👋 this is super cool! And extremely useful! I use Nest and have been looking at using https://github.com/supabase/gotrue for an OAuth server. And then I found this, perfect!

And now for my request, could you add the Twitch provider? I use https://github.com/Nigh7Sh4de/passport-twitch-new currently. With some time I could implement it myself, but I wanted to post this issue first in case someone else gets to it before me.

Note: You should add the hacktoberfest topic to this repo to make it eligible for the event!

**Comment by mjangir** [comment]
Sure @alexweininger thanks for the recommendation. Will do that shortly.

**Comment by alexweininger** [comment]
Awesome!

**Comment by mjangir** [comment]
@alexweininger Added Twitch authentication in the package. Please visit
https://www.npmjs.com/package/@nestjs-hybrid-auth/twitch
https://nestjs-hybrid-auth.manishjangir.com/docs/providers/twitch

**Comment by mjangir** [comment]
Added Twitch authentication. Closing this issue.
